name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5-dev libssl-dev libffi-dev \
          git unzip openjdk-17-jdk

    # ===== AUTOMATIC LINUX SDK SETUP =====
    - name: Set up Android SDK
      run: |
        mkdir -p ~/android-sdk/cmdline-tools
        cd ~/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip -d latest
        rm commandlinetools-linux-11076708_latest.zip

        echo "ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
        echo "~/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept licenses
      run: |
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android tools
      run: |
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"
    # ===== END SDK SETUP =====

    - name: Install Buildozer
      run: |
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android release
        mv bin/*.apk app-unsigned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: app-unsigned.apk
