name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5-dev libssl-dev libffi-dev \
          git unzip openjdk-17-jdk

    # ===== PROVEN ANDROID SDK SETUP =====
    - name: Set up Android SDK
      run: |
        # 1. Create proper directory structure
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        
        # 2. Download and extract tools (Linux version)
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        mv cmdline-tools latest
        rm commandlinetools-linux-11076708_latest.zip
        
        # 3. Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
        # 4. Verify installation
        ls -la $HOME/android-sdk/cmdline-tools/latest/bin/
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --list

    - name: Accept Android licenses
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android components
      run: |
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"
        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
    # ===== END SDK SETUP =====

    - name: Install Buildozer
      run: |
        pip install buildozer cython

    - name: Update buildozer.spec
      run: |
        sed -i "s|android.sdk_path = .*|android.sdk_path = $HOME/android-sdk|g" buildozer.spec
        echo "android.ndk_path = $HOME/android-sdk/ndk/25.2.9519653" >> buildozer.spec

    - name: Build unsigned APK
      run: |
        buildozer -v android release
        mv bin/*-release-unsigned.apk app-unsigned.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: app-unsigned.apk
