- name: Set up Android SDK
  run: |
    # Create the correct directory structure
    mkdir -p $HOME/android-sdk/cmdline-tools/latest
    cd $HOME/android-sdk/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    unzip commandlinetools-linux-11076708_latest.zip
    # Move contents directly into 'latest' (critical step!)
    mv cmdline-tools/* latest/
    rm -rf cmdline-tools commandlinetools-linux-11076708_latest.zip

    # Verify sdkmanager exists
    ls -la $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager

- name: Set up environment variables
  run: |
    echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
    echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
    echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

- name: Accept Android licenses
  run: |
    yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

- name: Install Android tools
  run: |
    $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"
    echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
